spring:
    mongodb:
      uri: mongodb://manoj:manoj@localhost:27017/customer?authSource=admin

server:
  port: 8084

logging:
  level:
    org.springframework.data.mongodb.core: DEBUG
    org.mongodb.driver: DEBUG