spring:
  data:
    mongodb:
      username: manoj
      password: manoj
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin
  kafka:
    consumer:
      group-id: paymentGroup,orderGroup
      auto-offset-reset: earliest
      bootstrap-service: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: orderConfirmation.OrderConfirmation:xyz.manojraw.ecommerce.notification.kafka.OrderConfirmation,paymentNotificationRequestDto.PaymentNotificationRequestDto:xyz.manojraw.ecommerce.notification.kafka.PaymentConfirmation
  mail:
    host: localhost
    port: 1025
    username: manoj
    password: manoj
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

server:
  port: 8088