spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order
    username: manoj
    password: manoj
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: order-service

server:
  port: 8086