spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order
    username: manoj
    password: manoj
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  application:
    config:
      customer-url: http://localhost:8084/api/v1/customers
      product-url: http://localhost:8085/api/v1/products
      payment-url: http://localhost:8086/api/v1/payments

server:
  port: 8086